/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActionColumn: typeof import('./src/components/panel/column/ActionColumn.vue')['default']
    AuthMenu: typeof import('./src/components/auth/AuthMenu.vue')['default']
    CircularProgress: typeof import('./src/components/panel/CircularProgress.vue')['default']
    ColumnText: typeof import('./src/components/panel/column/ColumnText.vue')['default']
    EmployerRow: typeof import('./src/components/panel/rows/EmployerRow.vue')['default']
    HeaderComp: typeof import('./src/components/global/layout/HeaderComp.vue')['default']
    InfoColumns: typeof import('./src/components/panel/column/InfoColumns.vue')['default']
    InfoPanel: typeof import('./src/components/panel/InfoPanel.vue')['default']
    InputGlobal: typeof import('./src/components/global/InputGlobal.vue')['default']
    MenuLeftIcon: typeof import('./src/components/icons/MenuLeftIcon.vue')['default']
    NotificationIcon: typeof import('./src/components/icons/NotificationIcon.vue')['default']
    PanelRows: typeof import('./src/components/panel/PanelRows.vue')['default']
    PanelTable: typeof import('./src/components/panel/PanelTable.vue')['default']
    ListItemMenu: typeof import('./src/components/layout/ListItemMenu.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchIcon: typeof import('./src/components/icons/SearchIcon.vue')['default']
    SidebarMenu: typeof import('./src/components/SidebarMenu.vue')['default']
}
}
