/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AuthMenu: typeof import('./src/components/auth/AuthMenu.vue')['default']
    CircularProgress: typeof import('./src/components/panel/CircularProgress.vue')['default']
    InputGlobal: typeof import('./src/components/global/InputGlobal.vue')['default']
    ListItemMenu: typeof import('./src/components/layout/ListItemMenu.vue')['default']
    PanelRows: typeof import('./src/components/panel/PanelRows.vue')['default']
    PanelTable: typeof import('./src/components/panel/PanelTable.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SidebarMenu: typeof import('./src/components/SidebarMenu.vue')['default']
  }
}
